version: '3.0'
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "docker"
      POSTGRES_USER: "docker"
      POSTGRES_DB: "docker"
    ports:
      - "5432:5432"
    volumes:
      - ~/.volumes/postgres:/var/lib/postgresql/data
    expose:
      - 5432
